# Generated by Django 5.2 on 2025-05-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_delete_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nonbre',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
    ]
