# Generated by Django 5.2 on 2025-06-06 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
