# Generated by Django 5.2 on 2025-06-06 14:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_pais_empleado_fecha_nac_empleado_pais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
